resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/ttakamura/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: rspec
    file: flight-school/build.yml
